# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - DogCat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Rust
        shell: cmd
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          %USERPROFILE%\.cargo\bin\rustup.exe install stable
          %USERPROFILE%\.cargo\bin\rustup.exe default stable

      - name: Verify virtual environment activation
        shell: cmd
        run: |
          venv\Scripts\activate.bat
          python --version
      
      - name: Log and verify dependencies
        shell: cmd
        run: |
          type requirements.txt
          venv\Scripts\activate.bat
          pip check
      
      - name: Upgrade pip and install dependencies
        shell: cmd
        run: |
          venv\Scripts\activate.bat
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Zip artifact for deployment
        shell: pwsh
        run: |
          Compress-Archive -Path * -DestinationPath release.zip -Force -Exclude 'venv', '.git', 'tests'
      
            - name: Upload artifact for deployment jobs
              uses: actions/upload-artifact@v4
              with:
                name: python-app
                path: |
                  release.zip
                  !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_554FC51F28E24E3EAAB9914A0D87BFD7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0E71FCA47DF447B186CC2206A94614C3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ED3C338CF6314ACCA73E1439157FFC90 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'DogCat'
          enable-logging: true 
